<?php
// $Id$

/**
 * @file
 * Provides configuration page to choose a menu to pull items from and create a custom menu using those items.
 */

// =================================
// = Implements hook_permission(). =
// =================================

function better_mm_permission() {
	$permission = array(
		'administer better mm' => array(
			'title' => t('Administer Better Mega Menu'),
			'description' => t('Configure Better Mega Menu Settings.'),
		),
	);
	return $permission;
}

// ===========================
// = Implements hook_menu(). =
// ===========================

function better_mm_menu() {
	$items['admin/structure/better_mm'] = array(
		'title' => t('Better Mega Menu Settings'),
		'description' => t('Configure Better Mega Menu Settings.'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('better_mm_admin_settings'),
		'access arguments' => array('administer better mm'),
	);
	return $items;
}

// ================================
// = Construct admin settins form =
// ================================

function better_mm_admin_settings($form, &$form_state) {
  $wide_access = FALSE;
  $mega_access = FALSE;
	
  $form['bmm_menu'] = array(
    '#title' => t('Select Menu'),
	  '#type' => 'select',
	  '#options' => better_mm_get_options('menus'),
	  '#default_value' => variable_get('bmm_menu', 'main-menu'),
	  '#ajax' => array(
	    'callback' => 'better_mm_menu_items_ajax_callback',
	    'wrapper' => 'bmm-menu-items',
	    'method' => 'replace',
	    'effect' => 'fade',
	  ),
	);
	$form['bmm_menu_items_fieldset'] = array(
    '#title' => t("Menu Items"),
    '#prefix' => '<div id="bmm-menu-items">',
    '#suffix' => '</div>',
    '#type' => 'fieldset',
    '#description' => t('Description here.'),
	);
	
	$menu_selection = !empty($form_state['values']['bmm_menu']) ? $form_state['values']['bmm_menu'] : 'main-menu';
	$menu_items = menu_navigation_links($menu_selection);
	
	$form['menu_items'] = array(
		'#type' => 'value',
		'#value' => $menu_items,
	);
	
	foreach ($menu_items as $menu_item) {
		$item_name = $menu_item['title'];
		$item_machine_name = str_replace(' ', '-', strtolower($item_name));
		$variable_name = 'bmm_style_' . $item_machine_name;
		$form['bmm_menu_items_fieldset']['bmm_menu_item_' . $item_machine_name] = array(
			'#type' => 'fieldset',
			'#title' => t($item_name),
		);
		$form['bmm_menu_items_fieldset']['bmm_menu_item_' . $item_machine_name][$variable_name] = array(
			'#type' => 'select',
			'#title' => t('Menu Item Style'),
			'#options' => better_mm_get_options('styles'),
			'#default_value' => variable_get($variable_name, 'standard'),
			'#prefix' => '<div id="bmm-menu-item-' . $item_machine_name . '-settings" class="bmm-menu-item-settings">',
			'#suffix' => '</div>',
			'#ajax' => array(
 				'callback' => 'better_mm_style_ajax_callback',
 				'wrapper' => 'bmm-style-settings-' . $item_machine_name,
 				'method' => 'replace',
 				'effect' => 'fade',
			),
		);
		$form['bmm_menu_items_fieldset']['bmm_menu_item_' . $item_machine_name]['bmm_menu_' . $item_machine_name . '_style_settings_subset'] = array(
			'#type' => 'fieldset',
			'#prefix' => '<div id="bmm-style-settings-' . $item_machine_name . '" class="bmm-style-settings">',
			'#suffix' => '</div>',
		);
		
		$bmm_item_style = !empty($form_state['triggering_element']['#value']) ?
 			$form_state['triggering_element']['#value'] : 'standard';
		
		if ($bmm_item_style == 'standard') {
		  $wide_access = FALSE;
		  $mega_access = FALSE;
	    $description = '<p>There are no settings available for a standard menu item.</p>';
	  }
		if ($bmm_item_style == 'wide') {
			$wide_access = TRUE;
			$mega_access = FALSE;
			$description = '<h4>Wide Menu Settings</h4>';
		}
		if ($bmm_item_style == 'mega') {
			$mega_access = TRUE;
			$wide_access = FALSE;
			$description = '<h4>Mega Menu Settings</h4>';
		}
		// This will need to be updated with a call to a function that returns the image path.
		// Used for displaying a preview of the uploaded image on "Wide" items.
		$image_path = '/sites/default/files/logo.png';
		
		$form['bmm_menu_items_fieldset']['bmm_menu_item_' . $item_machine_name]['bmm_menu_' . $item_machine_name . '_style_settings_subset']['bmm_menu_item_' . $item_machine_name . '_' . $bmm_item_style . '_description'] = array(
			'#type' => 'markup',
			'#markup' => $description,
		);
		$form['bmm_menu_items_fieldset']['bmm_menu_item_' . $item_machine_name]['bmm_menu_' . $item_machine_name . '_style_settings_subset']['bmm_menu_item_' . $item_machine_name . '_wide_image'] = array(
			'#access' => $wide_access,
			'#type' => 'item',
			'#markup' => theme('thumbnail', array(
				'path' => $image_path,
				'width' => 100,
				'height' => 100,
				'alt' => t('Preview Image'),
			)),
		);
		$form['bmm_menu_items_fieldset']['bmm_menu_item_' . $item_machine_name]['bmm_menu_' . $item_machine_name . '_style_settings_subset']['bmm_menu_item_' . $item_machine_name . '_wide_setting'] = array(
		  '#access' => $wide_access,
		  '#type' => 'file',
		  '#title' => t('Image Upload'),
			'#description' => t('Select an image that is at least @dimensionspx and maximum @filesize.', array(
				'@dimensions' => '100x100',
				'@filesize' => format_size(file_upload_max_size()),
			)),
		);
		$form['bmm_menu_items_fieldset']['bmm_menu_item_' . $item_machine_name]['bmm_menu_' . $item_machine_name . '_style_settings_subset']['bmm_menu_item_' . $item_machine_name . '_mega_setting'] = array(
			'#access' => $mega_access,
			'#type' => 'textarea',
			'#title' => t('Mega Menu Code'),
			'#description' => t('Add html code for Mega Menu block here.'),
			'#default_value' => variable_get('bmm_' . $item_machine_name . '_mega', ''),
		);
	}
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Save Configuration'),
	);
	return $form;
}

// ==============================
// = Admin form submit callback =
// ==============================

function better_mm_admin_settings_submit(&$form, &$form_state) {
	$menu_items = $form_state['values']['menu_items'];
	variable_set('bmm_menu', $form_state['values']['bmm_menu']);
	foreach ($menu_items as $menu_item) {
		$item_title = str_replace(' ', '-', strtolower($menu_item['title']));
		variable_set('bmm_style_' . $item_title, $form_state['values']['bmm_style_' . $item_title]);
		$item_style = variable_get('bmm_style_' . $item_title);
		if ($item_style != 'standard') {
		  variable_set('bmm_' . $item_title . '_' . $item_style, $form_state['values']['bmm_menu_item_' . $item_title . '_' . $item_style . '_setting']);
		}
	}
	drupal_set_message('Configuration has been saved.');
}

// ==================================================
// = Ajax callback for menu items of selected menu. =
// ==================================================

function better_mm_menu_items_ajax_callback($form, $form_state) {
	return $form['bmm_menu_items_fieldset'];
}

// =======================================
// = Ajax callback for menu items style. =
// =======================================

function better_mm_style_ajax_callback($form, $form_state) {
	$index = $form_state['triggering_element']['#array_parents'];
	$menu_item = $form_state['triggering_element']['#name'];
	$menu_item = explode('_', $menu_item);
	$menu_item = $menu_item[2];
	
	return $form[$index[0]][$index[1]]['bmm_menu_' . $menu_item . '_style_settings_subset'];
}

// ==================================================
// = Get list of options for select list form item. =
// ==================================================

function better_mm_get_options($item) {
	if ($item == 'menus') {
		$options = menu_get_menus();
	}
	
	if ($item == 'styles') {
		$options = array(
			'standard' => 'Standard',
			'wide' => 'Wide',
			'mega' => 'Mega Menu',
		);	
	}
	return $options;
}