<?php
// $Id$

/**
 * @file
 * Provides configuration page to choose a menu to pull items from and create a custom menu using those items.
 */

// =================================
// = Implements hook_permission(). =
// =================================

function better_mm_permission() {
  $permission = array(
    'administer better mm' => array(
      'title' => t('Administer Better Mega Menu'),
      'description' => t('Configure Better Mega Menu Settings.'),
    ),
  );
  return $permission;
}

// ===========================
// = Implements hook_menu(). =
// ===========================

function better_mm_menu() {
  $items['admin/structure/better_mm'] = array(
    'title' => t('Better Mega Menu Settings'),
    'description' => t('Configure Better Mega Menu Settings.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('better_mm_admin_settings'),
    'access arguments' => array('administer better mm'),
  );
  return $items;
}

// ================================
// = Construct admin settins form =
// ================================

function better_mm_admin_settings($form, &$form_state) {
  $phone = '<div class="tel"><a href="tel:+12084890123">208.489.0123</a></div></span></div>';
  $mobile_default = variable_get('bmm_menu_below_mobile_nav');
  $mobile_default = !empty($mobile_default['value']) ? $mobile_default['value'] : $phone;
  $wide_access = FALSE;
  $mega_access = FALSE;
  
  $form['bmm_menu'] = array(
    '#title' => t('Select Menu'),
    '#type' => 'select',
    '#options' => better_mm_get_options('menus'),
    '#default_value' => variable_get('bmm_menu', 'main-menu'),
    '#ajax' => array(
      'callback' => 'better_mm_menu_items_ajax_callback',
      'wrapper' => 'bmm-menu-items',
      'method' => 'replace',
      'effect' => 'fade',
    ),
  );
  $form['bmm_menu_items_fieldset'] = array(
    '#title' => t("Menu Items"),
    '#prefix' => '<div id="bmm-menu-items">',
    '#suffix' => '</div>',
    '#type' => 'fieldset',
  );
  $form['bmm_menu_items_fieldset']['description_fieldset'] = array(
    '#type' => 'fieldset',
    '#title' => t('Help'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $form['bmm_menu_items_fieldset']['description_fieldset']['description'] = array(
    '#type' => 'markup',
    '#markup' => '<div id="better-mm-help-text">You can put some helpful text here.</div>',
  );
  
  $menu_selection = !empty($form_state['values']['bmm_menu']) ? $form_state['values']['bmm_menu'] : 'main-menu';
  $menu_items = menu_navigation_links($menu_selection);
  
  $form['menu_items'] = array(
    '#type' => 'value',
    '#value' => $menu_items,
  );
  foreach ($menu_items as $menu_item) {
    // menu item variables
    $item_name = $menu_item['title'];
    $item_machine_name = str_replace(' ', '-', strtolower($item_name));
    $menu_item_fieldset = 'bmm_menu_item_' . $item_machine_name;
    $variable_name = 'bmm_style_' . $item_machine_name;
    $style_settings_fieldset = 'bmm_menu_' . $item_machine_name . '_style_settings_subset';
    $mega_default = variable_get('bmm_menu_item_' . $item_machine_name . '_mega_setting');
    $mega_default = !empty($mega_default['value']) ? $mega_default['value'] : '';
    
    // Construct settings fields for each menu item.
    $form['bmm_menu_items_fieldset'][$menu_item_fieldset] = array(
      '#type' => 'fieldset',
      '#title' => t($item_name),
    );
    $form['bmm_menu_items_fieldset'][$menu_item_fieldset][$variable_name] = array(
      '#type' => 'select',
      '#title' => t('Menu Item Style'),
      '#options' => better_mm_get_options('styles'),
      '#default_value' => variable_get($variable_name, 'standard'),
      '#prefix' => '<div id="bmm-menu-item-' . $item_machine_name . '-settings" class="bmm-menu-item-settings">',
      '#suffix' => '</div>',
      '#ajax' => array(
         'callback' => 'better_mm_style_ajax_callback',
         'wrapper' => 'bmm-style-settings-' . $item_machine_name,
         'method' => 'replace',
         'effect' => 'fade',
      ),
    );
    $form['bmm_menu_items_fieldset'][$menu_item_fieldset][$style_settings_fieldset] = array(
      '#type' => 'fieldset',
      '#prefix' => '<div id="bmm-style-settings-' . $item_machine_name . '" class="bmm-style-settings">',
      '#suffix' => '</div>',
    );
    
    $nolink_default = variable_get('bmm_menu_item_' . $item_machine_name . '_nolink', '');
    $saved_style = variable_get('bmm_style_' . $item_machine_name, 'standard');
    $bmm_item_style = !empty($form_state['triggering_element']['#value']) ? 
      $form_state['triggering_element']['#value'] : $saved_style;
    
    if (($bmm_item_style == 'Upload') || ($bmm_item_style == 'Remove')) {
      $bmm_item_style = 'wide';
    }
        
    if ($bmm_item_style == 'standard') {
      $wide_access = FALSE;
      $mega_access = FALSE;
    }
    if ($bmm_item_style == 'wide') {
      $wide_access = TRUE;
      $mega_access = FALSE;
    }
    if ($bmm_item_style == 'advanced') {
      $mega_access = TRUE;
      $wide_access = FALSE;
    }
    
    $form['bmm_menu_items_fieldset'][$menu_item_fieldset][$style_settings_fieldset]['bmm_menu_item_' . $item_machine_name . '_nolink'] = array(
      '#type' => 'checkbox',
      '#title' => t('No link'),
      '#description' => t('Check this box to remove the link on this item.'),
      '#default_value' => $nolink_default,
    );
    $form['bmm_menu_items_fieldset'][$menu_item_fieldset][$style_settings_fieldset]['bmm_menu_item_' . $item_machine_name . '_wide_setting'] = array(
      '#access' => $wide_access,
      '#type' => 'managed_file',
      '#title' => t('Image Upload'),
      '#size' => 40,
      '#description' => t('Select an image that is at least @dimensionspx and maximum @filesize. Allowed extensions: png jpg jpeg',
      array(
        '@dimensions' => '100x100',
        '@filesize' => format_size(file_upload_max_size()),
      )),
	  '#upload_validators' => array(
        'file_validate_extensions' => array('png jpg jpeg'),
      ),
      '#upload_location' => 'public://menu_images/',
      '#default_value' => variable_get('bmm_menu_item_' . $item_machine_name . '_wide_setting', ''),
    );
    $form['bmm_menu_items_fieldset'][$menu_item_fieldset][$style_settings_fieldset]['bmm_menu_item_' . $item_machine_name . '_mega_setting'] = array(
      '#access' => $mega_access,
      '#type' => 'text_format',
      '#title' => t('Advanced Menu Item Code'),
      '#description' => t('Add html code for Advanced Menu block here.'),
      '#default_value' => $mega_default,
      '#format' => 'full_html',
      '#rows' => 10,
    );
  }
  $form['bmm_menu_mobile_fieldset'] = array(
    '#type' => 'fieldset',
    '#title' => t('Mobile Settings'),
  );
  $form['bmm_menu_mobile_fieldset']['bmm_menu_below_mobile_nav'] = array(
    '#type' => 'text_format',
    '#title' => t('Content Below Mobile Navigation Button'),
    '#description' => t('Enter content you want displayed under the mobile navigation button.'),
    '#default_value' => $mobile_default,
    '#format' => 'full_html',
  );
  $form['bmm_menu_mobile_fieldset']['secondary_items_fieldset'] = array(
    '#type' => 'fieldset',
    '#title' => t('Mobile Secondary Items'),
    '#collapsible' => TRUE,
  );
  $form['#tree'] = TRUE;
  
  if (empty($form_state['number_items'])) {
    $form_state['number_items'] = 1;
  }
  
  for ($i = 1; $i <= $form_state['number_items']; $i++) {
    $form['bmm_menu_mobile_fieldset']['secondary_items_fieldset']['bmm_menu_mobile_secondary_fieldset'][$i] = array(
      '#type' => 'fieldset',
      '#title' => t('Secondary Item ' . $i),
    );
    $form['bmm_menu_mobile_fieldset']['secondary_items_fieldset']['bmm_menu_mobile_secondary_fieldset'][$i]['title'] = array(
      '#type' => 'textfield',
      '#title' => t('Item Title'),
      '#size' => 20,
    );
    $form['bmm_menu_mobile_fieldset']['secondary_items_fieldset']['bmm_menu_mobile_secondary_fieldset'][$i]['href'] = array(
      '#type' => 'textfield',
      '#title' => t('Item URL'),
      '#description' => t('Use Drupal internal path, or absolute URL'),
    );
    $form['bmm_menu_mobile_fieldset']['secondary_items_fieldset']['bmm_menu_mobile_secondary_fieldset'][$i]['class'] = array(
      '#type' => 'textfield',
      '#title' => t('Item Class'),
      '#description' => t('Enter any classes you want added to this menu item.'),
    );
  }
  if ($i < 6) {
    $form['bmm_menu_mobile_fieldset']['secondary_items_fieldset']['add_item'] = array(
      '#type' => 'submit',
      '#value' => t('Add another item'),
      '#submit' => array('better_mm_add_item'),
    );
  }
  $form['#submit'][] = 'better_mm_admin_settings_submit';

  return system_settings_form($form);
}

// ==================================================
// = Ajax callback for menu items of selected menu. =
// ==================================================

function better_mm_menu_items_ajax_callback($form, $form_state) {
  return $form['bmm_menu_items_fieldset'];
}

// =======================================
// = Ajax callback for menu items style. =
// =======================================

function better_mm_style_ajax_callback($form, $form_state) {
  $index = $form_state['triggering_element']['#array_parents'];
  $menu_item = $form_state['triggering_element']['#name'];
  $menu_item = explode('_', $menu_item);
  $menu_item = $menu_item[2];
  
  return $form[$index[0]][$index[1]]['bmm_menu_' . $menu_item . '_style_settings_subset'];
}

// ===========================
// = Add item submit handler =
// ===========================

function better_mm_add_item($form, &$form_state) {
  $form_state['number_items']++;
  $form_state['rebuild'] = TRUE;
}

// ==============================
// = Admin form submit handler =
// ==============================

function better_mm_admin_settings_submit(&$form, &$form_state) {
  $below_mobile_nav = !empty($form_state['values']['bmm_menu_below_mobile_nav']['value']) ? 
    $form_state['values']['bmm_menu_below_mobile_nav']['value'] : '';
  $menu_items = !empty($form_state['values']['menu_items']) ? $form_state['values']['menu_items'] : '';
  $key = 0;
  $html = '<ul class="mega-menu mega-level-1 first hide-on-med-and-down">';
  $mobile_html = '<ul id="nav-mobile" class="side-nav">
        <div class="side-nav-header">
          <ul class="mobile-secondary">
            <li><div class="table"><div class="table-cell"><a href="/" class="light home"></a></div></div></li>
            <li><div class="table"><div class="table-cell"><a href="/contact" class="light contact"></a></div></div></li>
            <li><div class="table"><div class="table-cell"><a href="/typography" class="">Typo Graphy</a></div></div></li>
            <li><div class="table"><div class="table-cell"><a href="#!">Other Link</a></div></div></li>
            <li><div class="table"><div class="table-cell"><a href="#!">No More Than 5</a></div></div></li>
          </ul>
        </div>';
  $mobile_html .= '<ul class="main-menu-navigation">';
    
  if (!empty($menu_items)) {
    foreach ($menu_items as $menu_item) {
      $title = str_replace(' ', '-', strtolower($menu_item['title']));
      $style = $form_state['values']['bmm_style_' . $title];
      $nolink = $form_state['values']['bmm_menu_item_' . $title . '_nolink'];
      $fid = !empty($form_state['values']['bmm_menu_item_' . $title . '_wide_setting']) ? 
        $form_state['values']['bmm_menu_item_' . $title . '_wide_setting'] : '';
      $adv_content = !empty($form_state['values']['bmm_menu_item_' . $title . '_mega_setting']['value']) ?
        $form_state['values']['bmm_menu_item_' . $title . '_mega_setting']['value'] : '';
      $children = better_mm_get_children($menu_item);
      $l1_class = better_mm_get_li_class($key, $menu_items);
      $child_class = better_mm_get_child_class($children, $style);
      $class_list = $l1_class . $child_class;
      
      if ($menu_item['href'] == '<front>') {
        $url = url('<front>');
      } else {
        $url = '/' . drupal_get_path_alias($menu_item['href']);
      }
      
      // If a file has been uploaded, set file status to permanent.
      if (is_numeric($fid)) {
        $item = menu_get_item($menu_item['href']);
        $mlid = db_select('menu_links' , 'ml')
          ->condition('ml.link_path' , $item['href'])
          ->fields('ml' , array('mlid'))
          ->execute()
          ->fetchField();
        $file = file_load($fid);
        $file->status = FILE_STATUS_PERMANENT;
        file_save($file);
        file_usage_add($file, 'better_mm', 'menu-item', $mlid);
      }
      
      $html .= '<li class="' . $class_list . '"><a';
      $mobile_html .= '<li class="' . $class_list . '"><a';
      if ($nolink) {
        $html .= '>' . $menu_item['title'] . '</a>';
        $mobile_html .= '>' . $menu_item['title'] . '</a>';
      }
      if (!$nolink) {
        $html .= ' href="' . $url . '">' . $menu_item['title'] . '</a>';
        $mobile_html .= ' href="' . $url . '">' . $menu_item['title'] . '</a>';
      }
      
      if ($style == 'advanced') {
        // Generate HTML for advanced item drop down.
        if (!empty($adv_content)) {
          $html .= '<ul class="mega-level-2 ' . $style . '">';
          $html .= '<div class="inner row">' . $adv_content . '</div> <!-- end inner row -->';
          $html .= '</ul>';
        }
        $html .= '</li>';
      }
      if (($style == 'wide') || ($style == 'standard')) {
        // Generate HTMl for the children of wide or standard items.
        $html .= better_mm_menu_item_tree($style, $children, $fid);
      }
      $mobile_html .= better_mm_menu_item_tree($style, $children, $fid, TRUE);
      $key++;
    } // foreach menu_item
    $html .= '</ul>';
    $mobile_html .= '</ul>';
    $mobile_html .= '<div class="side-nav-footer center-align">
          &copy; Site Name
        </div>
      </ul>';
    // Add mobile nav button.
    $html .= '<span class="nav-button valign-wrapper hide-on-large-only">';
    $html .= '<div class="valign">';
    $html .= '<a href="#" data-activates="nav-mobile" class="button-collapse">';
    $html .= '<i class="material-icons">menu</i><span class="menu-text">menu</span></a>';
    // Add mobile code below mobile nav button.
    $html .= $below_mobile_nav;
  }
  variable_set('bmm_block_content', $html);
  variable_set('bmm_mobile_block_content', $mobile_html);
  //dsm($mobile_html, 'mobile html');
}

// ==================================================
// = Get list of options for select list form item. =
// ==================================================

function better_mm_get_options($item) {
  if ($item == 'menus') {
    $options = menu_get_menus();
  }
  
  if ($item == 'styles') {
    $options = array(
      'standard' => 'Standard',
      'wide' => 'Wide',
      'advanced' => 'Advanced',
    );  
  }
  return $options;
}

// ==========================
// = Get menu item children =
// ==========================

function better_mm_get_children($menu_item) {
  if ($menu_item['href'] == '<front>') {
    $path = url('<front>');
  } else {
    $path = $menu_item['href'];
  }
  $parent = menu_link_get_preferred($path);
  $parameters = array(
  	'active_trail' => array($parent['plid']),
  	'only_active_trail' => FALSE,
  	'min_depth' => $parent['depth']+1,
  	'max_depth' => $parent['depth']+1,
  	'conditions' => array('plid' => $parent['mlid']),
  );
  $children = menu_build_tree($parent['menu_name'], $parameters);
  
  return $children;
}

// ===================================
// = Get the class for the <li> item =
// ===================================

function better_mm_get_li_class($key, $array) {
  $last = count($array) - 1;
  
  if ($key == 0) {
    return 'first';
  }
  
  if ($key == $last) {
    return 'last';
  }
  
  if ($key & 1) {
    return 'even';
  } else {
    return 'odd';
  }
}

// =================================
// = Get child class for <li> item =
// =================================

function better_mm_get_child_class($children, $style = 'standard') {
  if ($style == 'advanced') {
    return ' unset-child';
  }
  
  if (!empty($children)) {
    return ' has-children';
  } else {
    return ' no-children';
  }
}

// =============================
// = Build menu item tree HTML =
// =============================

function better_mm_menu_item_tree($style, $children, $fid, $mobile = FALSE) {
  $result = '';
  if (!$mobile) {
    $file = new stdClass();
    $inline_css = '';
    if ($style == 'wide' && !empty($fid)) {
      if (is_numeric($fid)) {
        $file = file_load($fid);
        $uri = $file->uri;
        $file_url = file_create_url($uri);
        $inline_css = 'background-image: url(' . $file_url . '); background-repeat: no-repeat; background-position: 0 0;';
      }
    }
    $ul_class = 'mega-level-';
  }
  if ($mobile) {
    $ul_class = 'mobile-level-';
  }
  if (!empty($children)) {
    $key2 = 0;
    if ($mobile) {
      $result .= '<div class="plus-button"></div>';
    }
    $result .= '<ul class="' . $ul_class . '2 ' . $style . '"';
    if (!empty($inline_css)) {
      $result .= ' style="' . $inline_css . '"';
    }
    $result .= '>';
    foreach ($children as $child) {
      $title2 = $child['link']['link_title'];
      $children2 = better_mm_get_children($child['link']);
      $l2_class = better_mm_get_li_class($key2, $children);
      $child2_class = better_mm_get_child_class($children2);
      $class2_list = $l2_class . $child2_class;
      if ($child['link']['href'] == '<front>') {
        $url2 = url('<front>');
      } else {
        $url2 = '/' . drupal_get_path_alias($child['link']['href']);
      }
      $result .= '<li class="' . $class2_list . '"><a href="' . $url2 . '">' . $title2 . '</a>';
      $key2++;
      if (!empty($children2)) {
        $key3 = 0;
        $result .= '<div class="plus-button"></div><ul class="' . $ul_class . '3">';
        foreach ($children2 as $child2) {
          $title3 = $child2['link']['link_title'];
          $l3_class = better_mm_get_li_class($key3, $children2);
          if ($child2['link']['href'] == '<front>') {
            $url3 = url('<front>');
          } else {
            $url3 = '/' . drupal_get_path_alias($child2['link']['href']);
          }
          $result .= '<li class="' . $l3_class . '"><a href="' . $url3 . '">' . $title3 . '</a></li>';
          $key3++;
        } // foreach child2
        $result .= '</ul></li>';
      } else {
        $result .= '</li>';
      }
    } // foreach child
    $result .= '</ul></li>';
  } else {
    $result .= '</li>';
  }
  return $result;
}

// ================================
// = Implements hook_block_info() =
// ================================

function better_mm_block_info() {
  $blocks = array();
  $blocks['better_mm_menu_block'] = array(
    'info' => t('Better Mega Menu Block'),
  );
  $blocks['better_mm_mobile_block'] = array(
    'info' => t('Better Mega Menu Mobile Block'),
  );
  
  return $blocks;
}

// ================================
// = Implements hook_block_view() =
// ================================

function better_mm_block_view($delta = '') {
  $block = array();
  
  switch ($delta) {
    case 'better_mm_menu_block':
    $block['subject'] = '';
    $block['content'] = variable_get('bmm_block_content', '');
    break;
    
    case 'better_mm_mobile_block':
    $block['subject'] = '';
    $block['content'] = variable_get('bmm_mobile_block_content', '');
    break;
  }
  return $block;
}
