<?php
require_once(drupal_get_path('module', 'better_mm') . '/includes/helpers.php');

/**
 * Gets called after a node has been inserted to database.
 *
 * @param $node
 *   A node object
 *
 * @see hook_node_postsave()
 * @see hook_node_postupdate()
 * @see hook_node_postdelete()
 * @see hook_node_postinsert()
 */
function hook_post_action_bmm_node_postinsert($node) {
  $menu = $node->menu;
  $bmm = variable_get('bmm_menu', '');
  if ($menu['enabled']) {
    $parent = explode(':', $menu['parent']);
    $menu_name = $parent[0];
    if ($menu_name == $bmm) {
      $bmm_block_content = bmm_gen_block_html($bmm);
      variable_set('bmm_block_content', $bmm_block_content['html']);
      variable_set('bmm_mobile_block_content', $bmm_block_content['mobile']);
    }
  }
}

/**
 * Gets called after a node has been updated to database.
 *
 * @param $node
 *   A node object
 *
 * @see hook_node_postsave()
 * @see hook_node_postinsert()
 * @see hook_node_postdelete()
 * @see hook_node_postupdate()
 */
function hook_post_action_bmm_node_postupdate($node) {
  $menu = $node->menu;
  $bmm = variable_get('bmm_menu', '');
  if ($menu['enabled']) {
    $parent = explode(':', $menu['parent']);
    $menu_name = $parent[0];
    if ($menu_name == $bmm) {
      $bmm_block_content = bmm_gen_block_html($bmm);
      variable_set('bmm_block_content', $bmm_block_content['html']);
      variable_set('bmm_mobile_block_content', $bmm_block_content['mobile']);
    }
  } else {
      $bmm_block_content = bmm_gen_block_html($bmm);
      variable_set('bmm_block_content', $bmm_block_content['html']);
      variable_set('bmm_mobile_block_content', $bmm_block_content['mobile']);
  }
}

/**
 * Gets called after a node has been deleted from database.
 *
 * @param $node
 *   A node object
 *
 * @see hook_node_postsave()
 * @see hook_node_postinsert()
 * @see hook_node_postupdate()
 * @see hook_node_postdelete()
 */
function hook_post_action_bmm_node_postdelete($node) {
  $bmm = variable_get('bmm_menu', '');
  $bmm_block_content = bmm_gen_block_html($bmm);
  variable_set('bmm_block_content', $bmm_block_content['html']);
  variable_set('bmm_mobile_block_content', $bmm_block_content['mobile']);
}
